### PR TITLE
Feature 70/use min gap as a constraint in penaltymodels

### LINKED ISSUE #70: Use min gap as a constraint in penaltymodels
**Current Problem**
Currently, penaltymodels are generated without considering the `min_classical_gap`. Instead the `min_classical_gap` is maintained indirectly; dwavebinarycsp.stitch checks to see if the found penaltymodel satisfies the `min_classical_gap`, if not, it asks for a new penaltymodel.

**Proposed Solution**
Pass the user's requested `min_classical_gap` to the penaltymodel. In this way, the penaltymodel can use `min_classical_gap` as a bound.

Note: user makes this `min_classical_gap` specification from dwavebinarycsp's stitch(..).

### PR DESCRIPTION
**Pull request by m3ller**
Closes #70.

- Made changes so that min classical gap can now be added as a direct constraint in each penalty model (MIP, MaxGap, LP)
- Add corresponding unit tests to verify that the min classical gap parameter works

### CODE REVIEW

**Comment by arcondello** [comment]
I think this might not technically be backwards compatibility breaking. Because the default min-gap is 2 so models that could previously be constructed can no longer be.

**Comment by m3ller** [comment]
Note changes made since last approval:
* Made code changes to penaltymodel-cache
* Bumped up version numbers

**Comment by m3ller** [comment]
This is currently being blocked because there is some confusion between `classical_gap` and `min_classical_gap`.

**Comment by m3ller** [comment]
The `min_classical_gap` and `classical_gap` issue will be taken care of by the refactoring issue #78

**Pull request merged**
